### ISSUE TITLE
Blank screen on load

### ISSUE THREAD

**Issue by davetsay** [NASA-AMMOS/openmct-mcws#109]
**Describe the defect**
Mission reporting blank screen on load. Needs investigation with mission to verify.
https://jira.jpl.nasa.gov/browse/OMM-193

**Expected behavior**

**Steps To Reproduce**
1. 
2. 
3. 
4. 

**Environment (please complete the following information):**
 - Version []
 - Browser []

**Additional context**
Add any other context, code snippets, error messages, screen shots about the problem here.

**Comment by jvigliotta** [comment]
Met with the customer and determined this is no longer a reliably replicated issue. Will update original ticket with this information.
