### ISSUE TITLE
Should prevent use of user input in `innerHTML`

### ISSUE THREAD

**Issue by davetsay** [NASA-AMMOS/openmct-mcws#118]
**Describe the defect**
Allowing user input in `innerHTML` elements allows for malicious code injection.

**Expected behavior**
User should not be able to inject malicious code. Functionality should remain unchanged.

**Testing Instructions**
1. Regression Test Plots
2. Regression Test Flexible Layouts
3. Regression test hyperlink creation

**Environment (please complete the following information):**
 - Version []
 - Browser []

**Additional context**
Add any other context, code snippets, error messages, screen shots about the problem here.

|Criticality|Name|Description|
|---|---|---|
|crit1|Critical|Defect makes the software unusable for mission operations.|
|crit2|Major|Defect has significant impact on usability of delivered software for mission operations. User experience is difficult and/or cumbersome. Workaround available is arduous.|
|crit3|Moderate|Defect has moderate to mild impact on usability of delivered software for mission operations. User experience is degraded but workable.|
|crit4|Minor|Defect means software does not work as originally intended, but the defect has little impact on the usability of the delivered software.|

**Comment by jvigliotta** [comment]
This has been implemented
