### ISSUE TITLE
Notification time stamps should clarify time system

### ISSUE THREAD

**Issue by davetsay** [NASA-AMMOS/openmct-mcws#134]
**Describe the sustaining activity**
Clarify what time system is being used for notifications (generally should be UTC unless for example it is a space craft event).

**Expected behavior**
User should have full understanding of timestamp meaning in notifications.

**Testing Instructions**
1. 

**Additional context**
https://jira.jpl.nasa.gov/projects/OMM/issues/OMM-206

**Comment by jvigliotta** [comment]
Tracking: OMM-207
