### ISSUE TITLE
OMM Search results are unreliable when user has poor network conditions

### ISSUE THREAD

**Issue by jvigliotta** [NASA-AMMOS/openmct-mcws#143]
**Is your feature request related to a problem? Please describe.**
While simulating poor network conditions (1M down with 230ms latency) it was observed that search results are inconsistent and unreliable. Network requests issued with each character change in the search bar take a while to resolve and the search results displayed update along the way. The correct results were achieved by backspacing and retyping the last character.

**Describe the solution you'd like**
Either not having to retype the last character to get the correct results or possibly having an option to make search explicit with a button.

**Testing Instructions**
1. In Dev Tools lower the network to low latency.
2. Search for an item you know exists
3. Verify the last set of results are the ones that are related to the search term without having to retype the last character.

**Additional context**
This is stemming from an issue where the network conditions are suboptimal, that's not something that can be addressed.

**Comment by jvigliotta** [comment]
This may be fixed by this issue: https://github.com/nasa/openmct/issues/6179 which has been implemented in core Open MCT.

**Comment by davetsay** [comment]
@nltpe101 , this was fixed in a ticket, but we didn't track it. We can discuss with Erik. i think adding to test report is feasible. If not, we can add as a comment. Its a regression test, although I don't know that we have a specific regression for this.
