### ISSUE TITLE
Fix Missing origin verification in `postMessage` handler

### ISSUE THREAD

**Issue by davetsay** [NASA-AMMOS/openmct-mcws#163]
Tracking issue for:
- [x] https://github.com/NASA-AMMOS/openmct-mcws/security/code-scanning/2
- [x] https://github.com/NASA-AMMOS/openmct-mcws/security/code-scanning/3
- [x] https://github.com/NASA-AMMOS/openmct-mcws/security/code-scanning/4

**Comment by jvigliotta** [comment]
one of these was legit, the other two were false positives. We've remedied the one actual security issue.
