### ISSUE TITLE
Time Conductor (fixed time Date/Time split)

### ISSUE THREAD

**Issue by jvigliotta** [NASA-AMMOS/openmct-mcws#164]
**Describe the sustaining activity**
The time conductor received some design upgrades in core Open MCT, most notably 1) being able to change dates, times, and offsets more easily, and 2) being explicit in setting start and end bounds simultaneously.

Existing functionality should not be lost in that transistion
* [copy/paste from and into input fields](https://github.com/nasa/openmct/issues/7666)
* [history, or preset selection outside of time input popup](https://github.com/nasa/openmct/issues/7665)
* 
Time Systems (date picker based on isUTC)
* ERT (T divider, UTC)
* SCET (T divider, UTC)
* SCLK (Float value)
* LMST (M divider, SOL-2706M01:34:24.388)

**Expected behavior**

**Testing Instructions**
1. 

**Additional context**

**Comment by mudinthewater** [comment]
Thank you! I know this seems like a dumb request but the copy-paste of whole timestamp is definitely something that users do.

**Comment by jvigliotta** [comment]
> Thank you! I know this seems like a dumb request but the copy-paste of whole timestamp is definitely something that users do.

Not at all! This definitely makes sense and it's a great suggestion.

**Comment by davetsay** [comment]
@mudinthewater , im going to go over our notes on other changes you discussed with us, but feel free to add comments to this ticket.
