### ISSUE TITLE
Add config option to disallow unfiltered historical queries

### ISSUE THREAD

**Issue by chesterhawkins** [NASA-AMMOS/openmct-mcws#175]
https://jira.jpl.nasa.gov/browse/ASK-288

**Is your feature request related to a problem? Please describe.**
NISAR user training stipulates for users to filter on a historical session in OMM so that queries don't bog down the MariaDB query database. We’ve our web hosts and db hosts crash during important activities because of the amount of users sending unfiltered queries. We’d like a way to strictly enforce this instead of solely relying on user training.

**Describe the solution you'd like**
We’d like a config option that, when enabled, makes it so that historical queries are not even sent out if a user is not filtering on a session.

**Testing Instructions**
1. Navigate to a plot while not filtered on a session
2. Observe in network tab that an query not filtered by session is sent

**Comment by jvigliotta** [comment]
@davetsay we good to merge this in?
