### ISSUE TITLE
Build 4 Bug Fixes

### ISSUE THREAD

**Issue by jvigliotta** [NASA-AMMOS/openmct-mcws#187]
**Describe the defect**

Track issues found during build 4 which has some significant code changes and dependency upgrades.

- [x] Inability to import a Dataset (missing assignment of component instance to parent scope component variable)
- [x] User provider method issue (due to new required method in core UserAPI)
![Screenshot 2024-08-05 at 10 58 21 AM](https://github.com/user-attachments/assets/5af41577-cc19-4cf4-8891-bd0cc6496352)
- [x] Issue with channel table set component during destroy hook 
![Screenshot 2024-08-06 at 3 12 38 PM](https://github.com/user-attachments/assets/b28ae9da-8860-4e38-8f13-9dcd2793a2c4)
- [ ] Time conductor does not automatically extend to end of session with multiple sessions selected (this may not be an OMM issue, needs further investigation)
<img width="1519" alt="Screenshot 2024-08-16 at 15 04 23" src="https://github.com/user-attachments/assets/c3e160e3-7e17-4b0c-8223-0fdc0c3f4d8a">

**Expected behavior**

Should work as it had before the code changes/dependency upgrades.

**Additional context**

**Comment by davetsay** [comment]
moving time conductor bug to #29
