### ISSUE TITLE
[DEFECT] Alarms not being reported when connected to a real time session

### ISSUE THREAD

**Issue by chesterhawkins** [NASA-AMMOS/openmct-mcws#39]
Describe the defect
Alarms not being reported when connected to a real time session.

Steps to reproduce:
Connect to a real time session and navigate to a view that reports alarms.

Version - v5.0.0-b3
Browser - Chrome

**Comment by davetsay** [comment]
@jvigliotta , this is the same issue we were seeing with the other table views.

Wanted fixed before 7/13 deployment (7/14 is RDO)

**Comment by chesterhawkins** [comment]
![Screenshot 2023-06-26 at 2 20 05 PM](https://github.com/NASA-AMMOS/openmct-mcws/assets/22469372/fe2d0da1-6d2e-496a-b481-a8c90e3ea6d8)
