### ISSUE TITLE
[DEFECT] saves are issuing multiple PUT calls and they are subject to a race condition

### ISSUE THREAD

**Issue by davetsay** [NASA-AMMOS/openmct-mcws#51]
**Describe the defect**
Observed 2 or 3 puts on each save of an object.

**Expected behavior**
There can only be one.

**Steps To Reproduce**
1. 
2. 
3. 
4. 

**Environment (please complete the following information):**
 - Version []
 - Browser []

**Additional context**
Add any other context, code snippets, error messages, screen shots about the problem here.

|Criticality|Name|Description|
|---|---|---|
|crit1|Critical|Defect makes the software unusable for mission operations.|
|crit2|Major|Defect has significant impact on usability of delivered software for mission operations. User experience is difficult and/or cumbersome. Workaround available is arduous.|
|crit3|Moderate|Defect has moderate to mild impact on usability of delivered software for mission operations. User experience is degraded but workable.|
|crit4|Minor|Defect means software does not work as originally intended, but the defect has little impact on the usability of the delivered software.|

**Comment by jvigliotta** [comment]
Seems to be fixed, may have been observed on 4.10
