### ISSUE TITLE
[DEFECT] Can't delete objects created in older versions of OMM (Investigate)

### ISSUE THREAD

**Issue by jvigliotta** [NASA-AMMOS/openmct-mcws#59]
part of https://jira.jpl.nasa.gov/browse/OMM-177

**Describe the defect**
Objects in folders created before 5.0 can't seem to be modified by 5.0, specifically for removing objects.

**Expected behavior**
You should be able to remove objects in older version persistences.

**Steps To Reproduce**
1. Install 5.0 on top of an older persistence storage
2. Try to remove an old object

**Comment by mudinthewater** [comment]
Seems related to whatever is responsible for writing out the new persistence storage object. While 5.0 can read old persistence objects, and write new persistence objects, it appears to only be able to write the unmodified old persistence object. 

I understand the desired behavior is to instead replace the old object composition format with the new object composition format, so whatever is responsible for taking the internal new format and writing it out to the MIO is probably the culprit.
