### ISSUE TITLE
[DEFECT] Notebook snapshots of an EVR view take a long time

### ISSUE THREAD

**Issue by jvigliotta** [NASA-AMMOS/openmct-mcws#60]
**Describe the defect**
Title says it all, notebook snapshots of an EVR view seem to be slow, this needs investigation.

**Expected behavior**
Should be normal compared to other snapshots.

**Steps To Reproduce**
1. Create a notebook snapshot of an EVR view
2. Create a notebook snapshot of another view
3. Note any differences in time it takes for snapshot to be taken

**Comment by jvigliotta** [comment]
Not able to reproduce at this moment, will reopen if it pops up again

**Comment by mudinthewater** [comment]
Issue is firefox-specific.
