### ISSUE TITLE
[INVESTIGATE] Plot not locking when clicked

### ISSUE THREAD

**Issue by jvigliotta** [NASA-AMMOS/openmct-mcws#61]
**Describe the defect**
In versions <5.0, a lock will show up on the top left by the legend, and the point you clicked will be frozen. Possible Mac vs PC issue? 

**Expected behavior**
This should 

**Steps To Reproduce**
1. Plot data
2. Click on plot

**Comment by mudinthewater** [comment]
Can be closed - workflow in 5.0 has been changed to: 

1. Plot data
2. Shift-click on plot. 

Wasn't documented anywhere I saw hence the confusion.
